### ISSUE TITLE
fix: make dargstack run on mac

### ISSUE THREAD

**Issue by dargmuesli** [dargmuesli/dargstack#48]
Executing DargStack on MacOS prints an error mentioning `shopt`. Fix that error.

A simple fix would be to package dargstack in a Docker image, in `alpine` for example. One could then mount a project's stack directory into a container running that image.

A challenge might be to deploy the Docker stack on the host machine outside the dargstack container. Most probably this can be achieved by mounting the docker socket into the dargstack container to give access to the host.
Another, maybe less preferable option would be to let the dargstack container generate configuration which can be read by the any host system afterwards.

@azolus started to rewrite the dargstack script in Go.

Reported by @PatrickMi in downstream issue https://github.com/maevsi/maevsi/issues/860.

**Comment by dargmuesli** [comment]
@PatrickMi @azolus I've added ideas on how to fix the max issue.
Would you be interested in creating a Dockerfile following the simple idea above, @PatrickMi? Would be an easy PR opportunity :moneybag: Me and @AlexSteckler can also work that out tomorrow.

**Comment by PatrickMi** [comment]
https://github.com/dargmuesli/dargstack/pull/50 shows how the Dargstack file can be used on macOS
